### ISSUE TITLE
Implement Lunar instead Bleak

### ISSUE THREAD

**Issue by ghost** [dentolos19/WxInjector#1]
How to implement new library [Lunar](https://github.com/Dewera/Lunar) instead Bleak for this injector?

**Comment by dentolos19** [comment]
Implementing Lunar into this injector? Since I noticed you forked this repository, I guess you're gonna be working on it, is that right?

**Comment by ghost** [comment]
> Implementing Lunar into this injector? Since I noticed you forked this repository, I guess you're gonna be working on it, is that right?

Yes. I forked just in case.

**Comment by dentolos19** [comment]
Okay, I'll give you some tips to how to implement the new library into this project. First of all, you will be only working with two files which is [`WnMain.xaml`](https://github.com/dentolos19/WxInjector/blob/master/WxInjector/Graphics/WnMain.xaml) and [`WnMain.xaml.cs`](https://github.com/dentolos19/WxInjector/blob/master/WxInjector/Graphics/WnMain.xaml.cs).

Since there is only one method to inject the DLL into process with Lunar, you can remove the [`MethodBox`](https://github.com/dentolos19/WxInjector/blob/1.3.1/WxInjector/Graphics/WnMain.xaml#L39) and then update the [`FlagBox`](https://github.com/dentolos19/WxInjector/blob/1.3.1/WxInjector/Graphics/WnMain.xaml#L44) to include the [new mapping flags](https://github.com/Dewera/Lunar#mappingflags-enum).

And then for the internal code, you can change [`InjectToProcess`](https://github.com/dentolos19/WxInjector/blob/1.3.1/WxInjector/Graphics/WnMain.xaml.cs#L41) and [`EjectFromProcess`](https://github.com/dentolos19/WxInjector/blob/1.3.1/WxInjector/Graphics/WnMain.xaml.cs#L87) to use the new library. The rest of the internal code will not need to be changed.

**Comment by ghost** [comment]
> Okay, I'll give you some tips to how to implement the new library into this project. First of all, you will be only working with two files which is [`WnMain.xaml`](https://github.com/dentolos19/WxInjector/blob/master/WxInjector/Graphics/WnMain.xaml) and [`WnMain.xaml.cs`](https://github.com/dentolos19/WxInjector/blob/master/WxInjector/Graphics/WnMain.xaml.cs).
> 
> Since there is only one method to inject the DLL into process with Lunar, you can remove the [`MethodBox`](https://github.com/dentolos19/WxInjector/blob/1.3.1/WxInjector/Graphics/WnMain.xaml#L39) and then update the [`FlagBox`](https://github.com/dentolos19/WxInjector/blob/1.3.1/WxInjector/Graphics/WnMain.xaml#L44) to include the [new mapping flags](https://github.com/Dewera/Lunar#mappingflags-enum).
> 
> And then for the internal code, you can change [`InjectToProcess`](https://github.com/dentolos19/WxInjector/blob/1.3.1/WxInjector/Graphics/WnMain.xaml.cs#L41) and [`EjectFromProcess`](https://github.com/dentolos19/WxInjector/blob/1.3.1/WxInjector/Graphics/WnMain.xaml.cs#L87) to use the new library. The rest of the internal code will not need to be changed.

Ok. Thank you so much!

**Comment by ghost** [comment]
i forgot to ask you @dentolos19 . what use instead Methodbox?

**Comment by dentolos19** [comment]
> what use instead Methodbox?

You could just remove it entirely as Lunar seems to only have one method to inject DLLs.
